require(knitr)
require(markdown)
# setwd("~/GitHub repositories/gettingandcleaningdata")
setwd("~/Repositories/Coursera/gettingandcleaningdata")
knit("run_analysis.Rmd", encoding="ISO8859-1")
markdownToHTML("run_analysis.md", "run_analysis.html")
